### ISSUE TITLE
DS Hangs when docked on multi monitor setup [OS X]

### ISSUE THREAD

**Issue by makahn** [FRC-Utilities/QDriverStation#16]
Driver station hangs when window mode is set to docked on a multi-monitor OS X setup.  

Can be avoided by leaving the window mode set to "Display Normally"

**Comment by alex-spataru** [comment]
Thanks for the report! 

What version of the QDriverStation are you running and which version of Mac OS are you using?

**Comment by younters** [comment]
Somewhat related, on OS X El Capitan, when the system dock is moved to the left side, the window by default is underneath the dock.

**Comment by alex-spataru** [comment]
@younters Thanks! I will change the functions used to calculate the width of the window when docked, hopefully that could help to solve this issue.

**Comment by alex-spataru** [comment]
@younters I fixed your issue with the latest commit, see the attached screenshot for further reference.
![screenshot](https://cloud.githubusercontent.com/assets/4225542/13772020/73eef862-ea57-11e5-972e-d21cfddf9d0d.png)

@makahn I already know what causes the DS to hang in a multi-monitor setup. I will check if Qt allows me to get information about the current screen in which the application is displayed, if so, your issue should be easier for me to fix.

**Comment by makahn** [comment]
OS X 10.10.5
QDriverStation v0.14
- Sorry for the delay

**Comment by alex-spataru** [comment]
No worries, thanks for the information!

**Comment by alex-spataru** [comment]
@makahn With the latest version ([link](https://github.com/WinT-3794/QDriverStation/releases/tag/v16.06-beta)), does the QDriverStation still crash with your multi-monitor setup?

**Comment by alex-spataru** [comment]
The UI code of the QDriverStation was overhauled since this issue was opened. @makahn If you experience problems with the latest version of the QDriverStation, feel free to open another issue!
