### ISSUE TITLE
SDL joystick mappings are different from the official FRC Driver Station

### ISSUE THREAD

**Issue by alex-spataru** [FRC-Utilities/QDriverStation#2]
While implementing and testing the protocol, an theoretical problem has arisen: SDL generates different joystick mappings than the ones used by the official FRC Driver Station (which are provided with Xinput). As a side note, the generated mappings can change depending on your platform and OS/driver version.

This can pose a serious security threat for teams that do not compare the joystick input between the QDriverStation and the FRC Driver Station, because the program could cause unexpected and 'involuntary' robot movement. We could ignore this 'issue', but I would prefer to solve it....breaking a window with a robot is not a nice experience...

Some solutions that came to my mind are:
- Use a JSON file to process the data reported by SDL. This could lead to using a different file for each joystick, operating system and OS/driver version.
- Offering an option to re-map your joystick (and possibly upload them and share it with the community)
- Using the Gamepad API and assign static variables for each button and axis type (e.g A = 0, B = 1, etc)

Any ideas?

**Comment by weaversam8** [comment]
+1 :+1: We also have this issue, and it has definitely been something that would be more helpful. As it is right now, one of our linux drivers is thinking about making a change in our robot code to accommodate this... I'd rather not have to do that.

**Comment by alex-spataru** [comment]
Thanks! I will begin working on this issue in the next couple of days.

**Comment by alex-spataru** [comment]
I will begin testing [QGamepad](https://doc-snapshots.qt.io/qt5-5.7/qgamepad.html), this can hopefully provide a good solution to the joystick mappings and help us remove the SDL dependency.

**Comment by alex-spataru** [comment]
Closing this issue to avoid duplication with issue #40.
