### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by fovea1959** [FRC-Utilities/QDriverStation#41]
Running qdriverstation 16.08 on Win 7 results in "The program can't start because api-ms-win-core-libraryloader-l1-2-0.dll is missing from your computer.  Try reinstallation the pogram to fix this problem.".

What are the prerequisites for running this?

**Comment by alex-spataru** [comment]
As far as I know, the Windows installer comes with all the dependencies of the QDriverStation. I have found online that this issue can be solved by installing the DirectX End-User Runtimes (http://www.microsoft.com/en-us/download/confirmation.aspx?id=8109).

Anyways, I will check how the QDriverStation runs on a vanilla install of Windows 7. There is a possibility that I have failed to include some dependencies/DLLs, as I only tested the QDriverStation on Windows 10.

Thanks for the feedback!
