### ISSUE TITLE
smartdahsboard not working

### ISSUE THREAD

**Issue by quillford** [FRC-Utilities/QDriverStation#47]
smartdashboard worked fine with the 2016 control system and the qdriverstation 16, but it's not working with the 2017 control system and qdriverstation 17

**Comment by alex-spataru** [comment]
Hello, could you please describe what part of the SmartDashboard is not working? (e.g. if the QDriverStation does not open the SmartDashboard).

Thanks!

**Comment by quillford** [comment]
it doesn't open. if i manually open it, nothing comes up.

**Comment by alex-spataru** [comment]
Thanks, it is possible that the location of the SmartDashboard has changed. Just to be sure what is happening, could you upload one of your log files here?

**Comment by quillford** [comment]
https://hastebin.com/kacozeboba.sql

**Comment by quillford** [comment]
that's from 17.01.1

**Comment by alex-spataru** [comment]
Judging from the log file, it seems that QDriverStation tries to open your dashboard and does nothing, which probably means that the dashboard location or command has changed. I'll look at this issue tomorrow morning. 

Thanks for the report!
