### ISSUE TITLE
No z Axis 

### ISSUE THREAD

**Issue by BearzRobotics** [FRC-Utilities/QDriverStation#48]
On the Logitech joystick that came with the kit of parts a few years back, QDriverStation can't read the z value of the controller.

[Logs](https://github.com/FRC-Utilities/QDriverStation/files/778800/Wed.15.zip)

**Comment by alex-spataru** [comment]
Hello, did you try to test the joystick with other applications (such as the official FRC Driver Station)?

**Comment by BearzRobotics** [comment]
Yes, it works fine in the official driver station. It also didn't work in the [robotpy](http://robotpy.readthedocs.io/en/stable/) simulation which uses pygame (which uses sdl for joystick input.)

**Comment by alex-spataru** [comment]
It is possible that this issue can be fixed by registering your joystick to the [database](https://github.com/FRC-Utilities/QDriverStation/blob/master/lib/QJoysticks/etc/resources/SDL/Database.txt) file. Could you tell me the exact model of your joystick please?
