### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by jacksondm33** [FRC-Utilities/QDriverStation#59]
QDriverStation relies on LibDS and QJoysticks which are two separate git repositories. Instead of just copying the code whenever there is an update, it would be better to make these submodules.

**Comment by alex-spataru** [comment]
I think that's a good idea. I will make changes to the repository configuration and build instructions later this evening.

**Comment by StripedMonkey** [comment]
Is this going to happen as a nested git repository?

**Comment by StripedMonkey** [comment]
@alex-spataru *poke* I've started working on trying to update LibDS and it would be great if It wasn't nessicairy to update it in two places :) I can do it for you if you want.

**Comment by alex-spataru** [comment]
Closing this issue since we now manage dependencies with submodules.
