### ISSUE TITLE
Fail to compile with fresh clone

### ISSUE THREAD

**Issue by patrickelectric** [FRC-Utilities/QDriverStation#61]
```
../src/main.cpp:40:10: fatal error: EventLogger.h: No such file or directory
 #include <EventLogger.h>
```

**Comment by alex-spataru** [comment]
Hi, sorry for the late reply!
I will try to compile the QDriverStation on my machine with a fresh clone. For the moment, could you please let me know your operating system and version?

**Comment by alex-spataru** [comment]
As a side note, the LibDS is now included as a submodule, you may need to run the following commands from the repository root folder:
```
git submodule init
git submodule update
```
Alternatively, clone the repository again with the following command
`git clone --recursive https://github.com/FRC-Utilities/QDriverStation`

**Comment by patrickelectric** [comment]
everything is working fine now, ty.
